/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RoomRoomUuidRouteRouteImport } from './routes/room/$roomUuid/route'
import { Route as RoomRoomUuidIndexRouteImport } from './routes/room/$roomUuid/index'
import { Route as RoomRoomUuidSetNameRouteImport } from './routes/room/$roomUuid/set-name'
import { Route as RoomRoomUuidScorersRouteImport } from './routes/room/$roomUuid/scorers'
import { Route as RoomRoomUuidEnterRouteImport } from './routes/room/$roomUuid/enter'
import { Route as RoomRoomUuidAdminIndexRouteImport } from './routes/room/$roomUuid/admin/index'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomRoomUuidRouteRoute = RoomRoomUuidRouteRouteImport.update({
  id: '/room/$roomUuid',
  path: '/room/$roomUuid',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomRoomUuidIndexRoute = RoomRoomUuidIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RoomRoomUuidRouteRoute,
} as any)
const RoomRoomUuidSetNameRoute = RoomRoomUuidSetNameRouteImport.update({
  id: '/set-name',
  path: '/set-name',
  getParentRoute: () => RoomRoomUuidRouteRoute,
} as any)
const RoomRoomUuidScorersRoute = RoomRoomUuidScorersRouteImport.update({
  id: '/scorers',
  path: '/scorers',
  getParentRoute: () => RoomRoomUuidRouteRoute,
} as any)
const RoomRoomUuidEnterRoute = RoomRoomUuidEnterRouteImport.update({
  id: '/enter',
  path: '/enter',
  getParentRoute: () => RoomRoomUuidRouteRoute,
} as any)
const RoomRoomUuidAdminIndexRoute = RoomRoomUuidAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => RoomRoomUuidRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/room/$roomUuid': typeof RoomRoomUuidRouteRouteWithChildren
  '/room/$roomUuid/enter': typeof RoomRoomUuidEnterRoute
  '/room/$roomUuid/scorers': typeof RoomRoomUuidScorersRoute
  '/room/$roomUuid/set-name': typeof RoomRoomUuidSetNameRoute
  '/room/$roomUuid/': typeof RoomRoomUuidIndexRoute
  '/room/$roomUuid/admin': typeof RoomRoomUuidAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/room/$roomUuid/enter': typeof RoomRoomUuidEnterRoute
  '/room/$roomUuid/scorers': typeof RoomRoomUuidScorersRoute
  '/room/$roomUuid/set-name': typeof RoomRoomUuidSetNameRoute
  '/room/$roomUuid': typeof RoomRoomUuidIndexRoute
  '/room/$roomUuid/admin': typeof RoomRoomUuidAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/room/$roomUuid': typeof RoomRoomUuidRouteRouteWithChildren
  '/room/$roomUuid/enter': typeof RoomRoomUuidEnterRoute
  '/room/$roomUuid/scorers': typeof RoomRoomUuidScorersRoute
  '/room/$roomUuid/set-name': typeof RoomRoomUuidSetNameRoute
  '/room/$roomUuid/': typeof RoomRoomUuidIndexRoute
  '/room/$roomUuid/admin/': typeof RoomRoomUuidAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/room/$roomUuid'
    | '/room/$roomUuid/enter'
    | '/room/$roomUuid/scorers'
    | '/room/$roomUuid/set-name'
    | '/room/$roomUuid/'
    | '/room/$roomUuid/admin'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/room/$roomUuid/enter'
    | '/room/$roomUuid/scorers'
    | '/room/$roomUuid/set-name'
    | '/room/$roomUuid'
    | '/room/$roomUuid/admin'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/room/$roomUuid'
    | '/room/$roomUuid/enter'
    | '/room/$roomUuid/scorers'
    | '/room/$roomUuid/set-name'
    | '/room/$roomUuid/'
    | '/room/$roomUuid/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  RoomRoomUuidRouteRoute: typeof RoomRoomUuidRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/room/$roomUuid': {
      id: '/room/$roomUuid'
      path: '/room/$roomUuid'
      fullPath: '/room/$roomUuid'
      preLoaderRoute: typeof RoomRoomUuidRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/room/$roomUuid/': {
      id: '/room/$roomUuid/'
      path: '/'
      fullPath: '/room/$roomUuid/'
      preLoaderRoute: typeof RoomRoomUuidIndexRouteImport
      parentRoute: typeof RoomRoomUuidRouteRoute
    }
    '/room/$roomUuid/set-name': {
      id: '/room/$roomUuid/set-name'
      path: '/set-name'
      fullPath: '/room/$roomUuid/set-name'
      preLoaderRoute: typeof RoomRoomUuidSetNameRouteImport
      parentRoute: typeof RoomRoomUuidRouteRoute
    }
    '/room/$roomUuid/scorers': {
      id: '/room/$roomUuid/scorers'
      path: '/scorers'
      fullPath: '/room/$roomUuid/scorers'
      preLoaderRoute: typeof RoomRoomUuidScorersRouteImport
      parentRoute: typeof RoomRoomUuidRouteRoute
    }
    '/room/$roomUuid/enter': {
      id: '/room/$roomUuid/enter'
      path: '/enter'
      fullPath: '/room/$roomUuid/enter'
      preLoaderRoute: typeof RoomRoomUuidEnterRouteImport
      parentRoute: typeof RoomRoomUuidRouteRoute
    }
    '/room/$roomUuid/admin/': {
      id: '/room/$roomUuid/admin/'
      path: '/admin'
      fullPath: '/room/$roomUuid/admin'
      preLoaderRoute: typeof RoomRoomUuidAdminIndexRouteImport
      parentRoute: typeof RoomRoomUuidRouteRoute
    }
  }
}

interface RoomRoomUuidRouteRouteChildren {
  RoomRoomUuidEnterRoute: typeof RoomRoomUuidEnterRoute
  RoomRoomUuidScorersRoute: typeof RoomRoomUuidScorersRoute
  RoomRoomUuidSetNameRoute: typeof RoomRoomUuidSetNameRoute
  RoomRoomUuidIndexRoute: typeof RoomRoomUuidIndexRoute
  RoomRoomUuidAdminIndexRoute: typeof RoomRoomUuidAdminIndexRoute
}

const RoomRoomUuidRouteRouteChildren: RoomRoomUuidRouteRouteChildren = {
  RoomRoomUuidEnterRoute: RoomRoomUuidEnterRoute,
  RoomRoomUuidScorersRoute: RoomRoomUuidScorersRoute,
  RoomRoomUuidSetNameRoute: RoomRoomUuidSetNameRoute,
  RoomRoomUuidIndexRoute: RoomRoomUuidIndexRoute,
  RoomRoomUuidAdminIndexRoute: RoomRoomUuidAdminIndexRoute,
}

const RoomRoomUuidRouteRouteWithChildren =
  RoomRoomUuidRouteRoute._addFileChildren(RoomRoomUuidRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  RoomRoomUuidRouteRoute: RoomRoomUuidRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
